project_id = "elio-website"

[api]
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[auth]
site_url = "https://eliocheesecakes.com"
additional_redirect_urls = ["http://127.0.0.1:4173/admin-account.html", "https://eliocheesecakes.com/admin-account.html"]
