import assert from 'node:assert/strict';
import JSZip from 'jszip';
import {heicContainer} from './helpers/image-fixtures.mjs';
import {makeProofArchive,readProof,zipFiles,sha256} from '../supabase/functions/order-backup/proof-archive.ts';
import {validateRecovery,fulfillmentCsv} from '../dist/assets/admin/recovery-data.js';
const id='11111111-1111-4111-8111-111111111111',path=id+'/22222222-2222-4222-8222-222222222222.png';
const image=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2FzQAAAAASUVORK5CYII=','base64'));
const review={id,reference:'ELIO-REVIEW',payment_status:'under_review',fulfillment_status:'pending_confirmation',proof_path:path,total_cents:10000,items:[{quantity:1,name:'Trio',unit_price_cents:10000,selection_labels:[],flavor_contents:[{name:'Matcha',quantity:3}]}]};
const data={source:'elio-paid-order-recovery',schema_version:1,generated_at:new Date().toISOString(),paid_orders:[],review_orders:[review],paid_history_count:0,active_order_ids:[id],active_count:1,active_total_cents:10000,payments:[],allocations:[],products:[],inventory:[],affiliates:[],affiliate_codes:[],affiliate_orders:[],affiliate_order_details:[],affiliate_ledger:[],affiliate_payouts:[]};
validateRecovery(data);assert.match(fulfillmentCsv(data),/under_review/);
const copied=await makeProofArchive(data,async p=>{assert.equal(p,path);return image;});assert.equal(copied.proof_count,1);
const archive=await JSZip.loadAsync(copied.bytes,{checkCRC32:true}),filename='proofs/ELIO-REVIEW/ELIO-REVIEW-payment-proof-1.png';assert.deepEqual(new Uint8Array(await archive.file(filename).async('uint8array')),image);assert.match(await archive.file('payment-proofs-index.csv').async('text'),/ELIO-REVIEW-payment-proof-1.png/);
const envelope=JSON.parse(await archive.file('recovery.json').async('text'));assert.equal(await sha256(new TextEncoder().encode(JSON.stringify(envelope.backup))),envelope.sha256);assert.equal(envelope.backup.proof_files[0].sha256,await sha256(image));assert.equal(envelope.backup.review_orders[0].payment_status,'under_review');
const originalHeic=heicContainer(),heicArchive=await makeProofArchive({...data,review_orders:[{...review,proof_path:path.replace('.png','.heic')}]},async()=>originalHeic),heicZip=await JSZip.loadAsync(heicArchive.bytes,{checkCRC32:true});assert.deepEqual(await heicZip.file('proofs/ELIO-REVIEW/ELIO-REVIEW-payment-proof-1.heic').async('uint8array'),new Uint8Array(originalHeic));
const complete=structuredClone(data);complete.review_orders=[];complete.paid_orders=[{...review,payment_status:'paid',fulfillment_status:'completed'}];complete.paid_history_count=1;complete.active_order_ids=[];complete.active_count=0;complete.active_total_cents=0;
const done=await makeProofArchive(complete,async()=>{throw Error('Should not download completed proof');});assert.equal(done.proof_count,0);assert.equal(done.snapshot.paid_orders.length,1);
for(const bad of ['../../secret',id+'/../other.png','https://outside.test/proof.png'])await assert.rejects(makeProofArchive({...data,review_orders:[{...review,proof_path:bad}]},async()=>image),/proof_files/);
await assert.rejects(makeProofArchive(data,async()=>new Uint8Array([1,2,3])),/proof_files/);await assert.rejects(makeProofArchive(data,async()=>{throw Error('Storage unavailable');}),/Storage unavailable/);
await assert.rejects(makeProofArchive({...data,review_orders:[{...review,proof_path:null}]}),/proof_files/);
const secondId='33333333-3333-4333-8333-333333333333';
await assert.rejects(makeProofArchive({...data,active_order_ids:[id,secondId],active_count:2,active_total_cents:20000,review_orders:[review,{...review,id:secondId,reference:'ELIO-OTHER'}]},async()=>image),/proof_files/);
assert.throws(()=>zipFiles([{name:'../evil',bytes:image}]),/configuration/);
let requested;assert.deepEqual(await readProof(path,{getCredentials:()=>({url:'https://storage.test',key:'fixture-only'}),request:async(url,options)=>{requested={url,options};return new Response(image);}}),image);assert(requested.url.endsWith('/object/authenticated/payment-proofs/'+path));assert.equal(requested.options.redirect,'error');
await assert.rejects(readProof(path,{getCredentials:()=>({url:'https://storage.test',key:'fixture-only'}),request:async()=>new Response('',{status:404})}),/proof_files/);
console.log('PASS actual private proof bytes, ZIP CRC/hash, under-review status, completion, missing/corrupt proofs and path safety.');
