import assert from 'node:assert/strict';
import {adminOrderView,orderFilters,inventoryMonthDrafts,clearAdminOrderView} from '../dist/assets/admin/progress-state.js';
import {acceptsReceipt} from '../dist/assets/shop/receipt-refresh.js';
const memory=new Map(),storage={getItem:key=>memory.get(key),setItem:(key,value)=>memory.set(key,value),removeItem:key=>memory.delete(key)};
let now=1000;const views=adminOrderView(storage,{now:()=>now});
views.save('owner-a','orders',{payment:'under_review',search:'Elio',date:'2026-10-03',upcoming:true});
assert.deepEqual(views.restore('owner-a'),{view:'orders',filters:{payment:'under_review',search:'Elio',date:'2026-10-03',upcoming:true,fulfillment:'',method:'',refund:''}});
assert.equal(views.restore('owner-b'),null);assert.equal(views.restore('owner-a'),null);
views.save('owner-a','orders',{});now+=30*60*1000;assert.equal(views.restore('owner-a'),null);
views.save('owner-a','orders',{});now--;assert.equal(views.restore('owner-a'),null);
views.save('owner-a','orders',{});views.save('owner-a','overview',{});assert.equal(views.restore('owner-a'),null);
views.save('owner-a','orders',{});clearAdminOrderView(storage);assert.equal(memory.size,0);
assert.equal(orderFilters({search:'x'.repeat(400),payment:'forged',fulfillment:'forged',method:'forged',refund:'forged',date:'2026-02-30',upcoming:'false'}).search.length,250);
assert.deepEqual(orderFilters({date:'2026-99-99',payment:'forged'}),{search:'',payment:'',fulfillment:'',method:'',refund:'',date:'',upcoming:false});
const blocked={getItem(){throw Error('blocked');},setItem(){throw Error('blocked');},removeItem(){throw Error('blocked');}};
assert.doesNotThrow(()=>adminOrderView(blocked).save('a','orders',{}));assert.equal(adminOrderView(blocked).restore('a'),null);
const drafts=inventoryMonthDrafts(),context={today:'2026-10-02',productIds:['vanilla'],months:['2026-10','2026-11']};
const october={dates:['2026-10-02','2026-10-03'],drafts:{vanilla:'30'},mode:'fill_unconfigured'};
drafts.remember('2026-10',october);october.drafts.vanilla='999';october.dates.push('2026-10-04');
drafts.remember('2026-11',{dates:['2026-11-01'],drafts:{vanilla:'45'},mode:'replace'});
assert.deepEqual(drafts.restore('2026-10',context),{dates:['2026-10-02','2026-10-03'],drafts:{vanilla:'30'},mode:'fill_unconfigured',adjusted:false});
assert.equal(drafts.restore('2026-11',context).drafts.vanilla,'45');
drafts.clear('2026-10');assert.deepEqual(drafts.restore('2026-10',context).drafts,{});assert.equal(drafts.restore('2026-11',context).drafts.vanilla,'45');
assert.equal(drafts.restore('2026-11',{...context,productIds:[]}).adjusted,true);
assert.deepEqual(drafts.restore('2026-11',{...context,today:'2026-11-02'}).dates,[]);
drafts.restore('2026-11',{...context,months:['2026-12','2027-01']});assert.deepEqual(drafts.restore('2026-11',context).drafts,{});
drafts.remember('2026-10',october);drafts.reset();assert.deepEqual(drafts.restore('2026-10',context).drafts,{});
const order={payment_status:'awaiting_payment',fulfillment_status:'pending_confirmation',payment_deadline:'2026-10-03T12:00:00Z'},time=Date.parse('2026-10-03T11:59:59Z');
assert.equal(acceptsReceipt(order,time),true);assert.equal(acceptsReceipt(order,time+1000),false);
for(const payment_status of ['under_review','paid','cancelled','rejected'])assert.equal(acceptsReceipt({...order,payment_status},time),false);
for(const fulfillment_status of ['cancelled','expired','completed','refunded'])assert.equal(acceptsReceipt({...order,fulfillment_status},time),false);
assert.equal(acceptsReceipt({...order,uploads_paused:true},time),false);assert.equal(acceptsReceipt({...order,refund_label:true},time),false);
assert.equal(acceptsReceipt({...order,order_source:'direct',payment_deadline:null},time),true);assert.equal(acceptsReceipt({...order,payment_deadline:null},time),false);
console.log('PASS staff-scoped view expiry/sign-out, month draft isolation/revalidation and receipt eligibility.');
