import assert from 'node:assert/strict';
import {selectionKey,mergeBasketItems,basketIncreaseLimit,productDrafts} from '../dist/assets/shop/basket-interactions.js';
import {accountReturn,temporaryOrderReadFailure} from '../dist/assets/admin/account-return.js';
const memory=()=>{const values=new Map();return {getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};};
const date='2026-10-03',flavors=[{id:'vanilla',name:'Vanilla',active:true,in_rotation:true},{id:'chocolate',name:'Chocolate',active:true,in_rotation:true}];
const fixed={id:'fixed',kind:'set',flavor_contents:[{...flavors[0],product_id:'vanilla',quantity:3}]},custom={id:'custom',kind:'custom_box',option_groups:[{id:'flavors',required_count:3,choices:flavors}]};
const inventory=(v,c=30)=>[{product_id:'vanilla',date,available:true,capacity:v,remaining:v},{product_id:'chocolate',date,available:true,capacity:c,remaining:c}];
const line=(product,quantity=1,selections={})=>({product_id:product.id,quantity,selections});
const first={flavors:{vanilla:1,chocolate:2}},reverse={flavors:{chocolate:2,unused:0,vanilla:1}};
assert.equal(selectionKey(first),selectionKey(reverse));
const combined=mergeBasketItems([line(custom,2,first),line(fixed),line(custom,3,reverse),line(custom,1,{flavors:{vanilla:2,chocolate:1}})]);
assert.deepEqual(combined.map(l=>l.quantity),[5,1,1]);assert.deepEqual(first,{flavors:{vanilla:1,chocolate:2}});
assert.deepEqual(mergeBasketItems([line(custom,999,first),line(custom,1,reverse)],999).map(l=>l.quantity),[999,1]);
assert.equal(basketIncreaseLimit([line(fixed)],0,[fixed],inventory(3),date).maximum,1);
assert.match(basketIncreaseLimit([line(fixed)],0,[fixed],inventory(3),date).message,/Vanilla.*for this date.*Choose another date/);
assert.equal(basketIncreaseLimit([line(fixed)],0,[fixed],inventory(5),date).maximum,1);
assert.equal(basketIncreaseLimit([line(fixed),line(custom,1,first)],0,[fixed,custom],inventory(6),date).maximum,1);
assert.equal(basketIncreaseLimit([line(fixed)],0,[fixed],inventory(6),date).message,'');
assert.equal(basketIncreaseLimit([line(fixed)],0,[fixed],[{product_id:'vanilla',date,available:true,capacity:null}],date).maximum,999);
assert.equal(basketIncreaseLimit([line(fixed,999)],0,[fixed],[{product_id:'vanilla',date,available:true,capacity:null}],date).maximum,999);
assert.match(basketIncreaseLimit([line(fixed,999)],0,[fixed],[{product_id:'vanilla',date,available:true,capacity:null}],date).message,/999/);
const repeated={...fixed,flavor_contents:[{...flavors[0],quantity:1},{...flavors[0],quantity:2}]};assert.equal(basketIncreaseLimit([line(repeated)],0,[repeated],inventory(3),date).maximum,1);
const store=memory();let time=1000;const drafts=productDrafts(store,()=>time);
drafts.save('custom',{flavors:{vanilla:1,chocolate:1}},2);assert.deepEqual(drafts.read(custom,date,inventory(10)),{selected:{flavors:{vanilla:1,chocolate:1}},quantity:2,adjusted:false});
const changed={...custom,option_groups:[{id:'flavors',required_count:3,choices:[flavors[0],{...flavors[1],active:false}]}]};assert.deepEqual(drafts.read(changed,date,inventory(10)),{selected:{flavors:{vanilla:1}},quantity:2,adjusted:true});
assert.deepEqual(drafts.read(custom,date,inventory(0)).selected,{flavors:{chocolate:1}});
time+=86400000;assert.equal(drafts.read(custom,date,inventory(10)),null);
drafts.save('custom',first,1);drafts.clear('custom');assert.equal(drafts.read(custom,date,inventory(10)),null);
const blocked=productDrafts({getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}});blocked.save('custom',first,1);assert.equal(blocked.read(custom,date,inventory(10)).quantity,1);
let clock=1000;const authStore=memory(),base={customer:true,storage:authStore,now:()=>clock};
for(const next of ['https://evil.test','//evil.test','order.html?to=https://evil.test','../order.html','manage.html','javascript:alert(1)'])assert.equal(accountReturn({...base,search:'?next='+encodeURIComponent(next)}).destination,'account.html');
const intent=accountReturn({...base,search:'?next=order.html'});assert.equal(intent.destination,'order.html#your-basket');clock+=5000;intent.remember();
assert.equal(accountReturn({...base,search:'',received:false}).toShop,false);assert.equal(accountReturn({...base,search:'',received:true}).toShop,true);
assert.equal(accountReturn({...base,customer:false,search:'?next=order.html',received:true}).toShop,false);
clock+=30*60*1000;assert.equal(accountReturn({...base,received:true}).toShop,false);intent.remember();intent.clear();assert.equal(accountReturn({...base,received:true}).toShop,false);
for(const error of [{status:401,uncertain:true},{status:403},{code:'42501'},{code:'PGRST301'},{code:'23505'}])assert.equal(temporaryOrderReadFailure(error),false);
for(const error of [{uncertain:true},new Error('Network failed'),{status:503},{status:429}])assert.equal(temporaryOrderReadFailure(error),true);
console.log('PASS customer friction: basket identity, shared-flavor limits, saved draft expiry/revalidation, safe auth returns, and refresh failure classification.');
