import assert from 'node:assert/strict';
import {backupSheetRequests,recoveryRows,decodeRecoveryRows} from '../supabase/functions/order-backup/sheets.js';
import {syncBackup,handle} from '../supabase/functions/order-backup/handler.ts';
import {createGoogleSheets,spreadsheetId} from '../supabase/functions/order-backup/google.ts';
import {fulfillmentCsv} from '../dist/assets/admin/recovery-data.js';
const data={schema_version:1,source:'elio-paid-order-recovery',generated_at:new Date().toISOString(),active_count:1,paid_history_count:1,active_total_cents:10000,active_order_ids:['order1'],paid_orders:[{id:'order1',reference:'ELIO-EXAMPLE',payment_status:'paid',fulfillment_status:'confirmed',total_cents:10000,buyer:{name:'=FORMULA',email:'dummy@example.test'},items:[{name:'Box',quantity:1,unit_price_cents:10000,selection_labels:[{quantity:3,label:'Vanilla'}]}]}],payments:[],allocations:[],products:[],inventory:[],affiliates:[],affiliate_codes:[],affiliate_orders:[{order_id:'order1',code:'BRENT',commission_bps:500}],affiliate_order_details:[],affiliate_ledger:[],affiliate_payouts:[]};
const sheets=['Orders','Items','Affiliates','Recovery','History'].map((title,sheetId)=>({properties:{title,sheetId,gridProperties:{rowCount:100,columnCount:26}}}));
const encoded=await recoveryRows(data);assert.deepEqual(await decodeRecoveryRows(encoded),data);const bad=structuredClone(encoded);bad[0][5]+='tampered';await assert.rejects(decodeRecoveryRows(bad),/checksum/);
const requests=await backupSheetRequests(data,sheets);assert.equal(requests.filter(r=>r.updateCells).length,5);assert(requests.some(r=>JSON.stringify(r).includes('Vanilla')));assert(requests.some(r=>JSON.stringify(r).includes('BRENT')));assert(requests.some(r=>JSON.stringify(r).includes('"stringValue":"=FORMULA"')));assert(!JSON.stringify(requests).includes('formulaValue'));
const completed=structuredClone(data);completed.paid_orders[0].fulfillment_status='completed';completed.active_order_ids=[];completed.active_count=0;completed.active_total_cents=0;completed.generated_at=new Date(Date.now()+1000).toISOString();const changed=await backupSheetRequests(completed,sheets,encoded,[]);const orders=changed.find(r=>r.updateCells?.range.sheetId===0);assert.equal(orders.updateCells.rows.length,5);assert(changed.find(r=>r.updateCells?.range.sheetId===4).updateCells.rows.length>5);
await assert.rejects(backupSheetRequests({...data,active_count:99},sheets),/counts/);await assert.rejects(backupSheetRequests(data,sheets.slice(1)),/missing/);
const large=structuredClone(data);large.paid_orders[0].instructions='🍰'.repeat(40000);assert.deepEqual(await decodeRecoveryRows(await recoveryRows(large)),large);
const fixed=structuredClone(data);fixed.paid_orders[0].items[0].selection_labels=[];fixed.paid_orders[0].items[0].flavor_contents=[{name:'Matcha',quantity:3}];
assert.match(fulfillmentCsv(fixed),/3 × Matcha/);
const fixedRows=await backupSheetRequests(fixed,sheets);assert.match(JSON.stringify(fixedRows.find(r=>r.updateCells?.range.sheetId===1)),/3 × Matcha/);
assert.equal(spreadsheetId('https://docs.google.com/spreadsheets/d/12345678901234567890/edit'),'12345678901234567890');assert.throws(()=>spreadsheetId('https://evil.test/a'));
let calls=[];const client={info:()=>({configured:false}),write:async()=>{throw Error('network');}};await syncBackup(client,async(action,payload)=>{calls.push({action,payload});return action==='order_backup_begin'?{lease_token:'lease',revision:1,spreadsheet_id:'sheet',snapshot:data}:{};});assert.equal(calls.at(-1).payload.error,'network');
globalThis.Deno={env:{get:()=>''}};assert.equal((await handle(new Request('https://backup.test',{method:'POST',headers:{'x-worker-token':'bad'},body:'{}'}))).status,401);
assert.deepEqual(createGoogleSheets({getEnv:()=>''}).info(),{configured:false});
console.log('PASS Google backup atomic batches, paid completion/history, affiliates, checksum, Unicode chunks, failures and authentication');
