import assert from 'node:assert/strict';
import {checkoutFailure} from '../dist/assets/shop/checkout-recovery.js';
import {attentionItems} from '../dist/assets/admin/needs-attention.js';
import {prepareOrderSave} from '../dist/assets/admin/order-edit-save.js';
assert.match(checkoutFailure({message:'Failed to fetch'}).message,/may already be saved/);
assert.equal(checkoutFailure({message:'Insufficient stock',code:'P0001'}).message,'Insufficient stock');
const now=Date.now(),old=new Date(now-7200000).toISOString(),recent=new Date(now-1000).toISOString();
const order={id:'o',reference:'ELIO-A',payment_status:'under_review',fulfillment_status:'pending_confirmation',created_at:old};
assert.equal(attentionItems({orders:[order]},now).length,1);
for(const change of [{created_at:recent},{refund_label:true},{payment_status:'paid'},{fulfillment_status:'cancelled'}])assert.equal(attentionItems({orders:[{...order,...change}]},now).length,0);
assert.equal(attentionItems({email_status:[{status:'sent',last_error:'old'}]}).length,0);
assert.equal(attentionItems({email_status:[{status:'failed',last_error:'network'}]}).length,1);
const original={id:'o',revision:1,total_cents:50000,payment_status:'paid',fulfillment_date:'2026-10-10',method:'pickup',items:[{name:'Box',quantity:1}]};
const checked={...original,fulfillment_date:'2026-10-11',subtotal_cents:50000,discount_cents:0,delivery_cents:0};let details;
const args={order:original,changes:{fulfillment_date:'2026-10-11'},idempotencyKey:'once',preview:async()=>checked,confirmTotalChange:async d=>{details=d;return true;}};
assert(await prepareOrderSave(args));assert.equal(details.oldDate,'2026-10-10');assert.equal(details.newDate,'2026-10-11');assert.equal(details.oldTotal,details.newTotal);
assert.equal(await prepareOrderSave({...args,confirmTotalChange:async()=>false}),null);
let current=true;await assert.rejects(prepareOrderSave({...args,isCurrent:()=>current,confirmTotalChange:async()=>{current=false;return true;}}),/form changed/);
console.log('PASS recovery wording, attention resolution and equal-price date edit confirmation');
