import assert from 'node:assert/strict';import ExcelJS from 'exceljs';import JSZip from 'jszip';import {buildRecoveryWorkbook,recoveryZip,recoveryJson} from '../dist/assets/admin/backup-export.js';import {createHash} from 'node:crypto';
const id='11111111-1111-4111-8111-111111111111',path=id+'/receipt.png',png=Uint8Array.from(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2FzQAAAAASUVORK5CYII=','base64'));
const order={id,reference:'ELIO-QA',payment_status:'under_review',fulfillment_status:'pending_confirmation',proof_path:path,total_cents:187158,subtotal_cents:167158,discount_cents:10000,delivery_cents:30000,buyer:{name:'=SUM(1,2)'},items:[{name:'Custom',quantity:2,unit_price_cents:83579,line_total_cents:167158,selection_labels:[{quantity:1,label:'Vanilla'},{quantity:2,label:'Cocoa'}]}]};
const data={schema_version:1,source:'elio-paid-order-recovery',generated_at:new Date().toISOString(),download_scope:'paid_review',active_count:1,active_order_ids:[id],active_total_cents:187158,paid_orders:[],paid_history_count:0,review_orders:[order],payments:[],allocations:[],products:[],inventory:[],affiliates:[],affiliate_codes:[],affiliate_orders:[],affiliate_order_details:[],affiliate_ledger:[],affiliate_payouts:[],notes:'x'.repeat(70000)};
const wb=buildRecoveryWorkbook(data,ExcelJS),bytes=await wb.xlsx.writeBuffer(),r=new ExcelJS.Workbook();await r.xlsx.load(bytes);assert.equal(r.getWorksheet('Orders').getCell('G2').value,'=SUM(1,2)');assert.equal(r.getWorksheet('Orders').getCell('Q2').value,1871.58);assert.equal(r.getWorksheet('Items').getCell('D2').value,'1 × Vanilla; 2 × Cocoa');let json='';r.getWorksheet('Recovery data').eachRow((row,n)=>{if(n>1)json+=row.getCell(2).value;});assert.deepEqual(JSON.parse(json),data);
const api=async(action,payload)=>{assert.equal(action,'proof_url');assert.equal(payload.order_id,id);return {url:'https://dzxyhckkkrzqpwpavngn.supabase.co/storage/v1/object/sign/payment-proofs/'+path+'?token=test'};};
const zip=await recoveryZip(data,api,{request:async()=>new Response(png)}),archive=await JSZip.loadAsync(zip.bytes,{checkCRC32:true});assert(archive.file('proofs/ELIO-QA/ELIO-QA-payment-proof-1.png'));assert.deepEqual(new Uint8Array(await archive.file('proofs/ELIO-QA/ELIO-QA-payment-proof-1.png').async('uint8array')),png);const envelope=JSON.parse(await archive.file('recovery.json').async('text'));assert.equal(envelope.sha256,createHash('sha256').update(JSON.stringify(envelope.backup)).digest('hex'));assert.equal(envelope.backup.proof_files[0].order_id,id);
await assert.rejects(recoveryZip(data,async()=>({url:'https://evil.example/receipt.png'})),/proof changed/i);await assert.rejects(recoveryZip(data,api,{request:async()=>new Response('failure',{status:503})}),/could not be downloaded/);await assert.rejects(recoveryZip(data,api,{request:async()=>new Response(new Uint8Array(5*1024*1024+1))}),/limit/);
const out=JSON.parse(await recoveryJson(data));assert.deepEqual(out.backup,data);console.log('PASS Excel literal values, money, flavors and lossless recovery chunks; actual proof ZIP bytes, labels, checksums, URL mismatch and download failures.');
