import assert from 'node:assert/strict';
import {firstAvailableDate,prepareCatalog,boxStock,basketStockIssues,customerBookingWindow,selectionPrice,availability} from '../dist/assets/shop/shop-rules.js';
const now=new Date('2026-09-24T01:00:00Z');
const settings={paused:false,production_weekdays:[1,2,3,4,5,6],fulfillment_weekdays:[0,1,2,3,4,5,6],cutoff_time:'10:00'};
const flavors=[{id:'a',name:'Vanilla',active:true,in_rotation:true,price_cents:0},{id:'b',name:'Matcha',active:true,in_rotation:true,price_cents:5000}];
const products=prepareCatalog({flavors,products:[{id:'set',kind:'set',active:true,price_cents:99000,lead_days:1,min_quantity:1,flavor_contents:[{product_id:'a',name:'Vanilla',quantity:2},{product_id:'b',name:'Matcha',quantity:1}]},{id:'custom',kind:'custom_box',active:true,price_cents:90000,lead_days:1,min_quantity:1}]}).products;
const inventory=[{product_id:'a',date:'2026-09-25',capacity:0,remaining:0},{product_id:'b',date:'2026-09-25',capacity:0,remaining:0},{product_id:'a',date:'2026-09-26',capacity:3,remaining:3}];
assert.equal(firstAvailableDate([],products,settings,inventory,now),'2026-09-26');
assert.equal(firstAvailableDate([{product_id:'set',quantity:2,selections:{}}],products,settings,inventory,now),'2026-09-27');
assert.equal(firstAvailableDate([],products,{...settings,paused:true},inventory,now),'');
assert.equal(customerBookingWindow(now).maxDate,'2026-10-31');
assert.equal(customerBookingWindow(new Date('2028-01-31T16:00:00Z')).maxDate,'2028-03-31');
assert.equal(boxStock(products[0],'2026-09-26',inventory),1);
assert.equal(selectionPrice(products[0],{}),99000);
assert.throws(()=>selectionPrice(products[0],{flavors:{a:3}}),/cannot be changed/);
assert.equal(selectionPrice(products[1],{flavors:{a:1,b:2}}),100000);
assert.equal(basketStockIssues([{product_id:'set',quantity:1,selections:{}},{product_id:'custom',quantity:1,selections:{flavors:{a:2,b:1}}}],products,inventory,'2026-09-26').length,1);
assert.equal(availability(products[0],'2026-11-01',settings,[],now).available,false);
const unavailable=prepareCatalog({flavors:flavors.map(f=>f.id==='b'?{...f,active:false}:f),products}).products;
assert.equal(boxStock(unavailable[0],'2026-09-26',inventory),0);
console.log('PASS 12 shop date, pricing, and shared-stock checks');
