import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir,mkdir} from 'node:fs/promises';
import {resolve,join,extname,sep} from 'node:path';
import {makeHarness} from '../backend/helpers.mjs';
import {accountingFixture} from '../backend/accounting-fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require(join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'playwright'));
const dep=createRequire(join(process.env.PGLITE_PACKAGE_ROOT,'package.json')),{PGlite}=dep('@electric-sql/pglite'),{pgcrypto}=dep('@electric-sql/pglite/contrib/pgcrypto');
const db=new PGlite({extensions:{pgcrypto}}),project=resolve(import.meta.dirname,'../..'),root=join(project,'dist'),origin='https://pos.test',out=join(project,'test-results/pos');await mkdir(out,{recursive:true});
await db.exec(await readFile(join(project,'tests/backend/bootstrap.sql'),'utf8'));
for(const name of (await readdir(join(project,'supabase/migrations'))).filter(n=>n.endsWith('.sql')).sort()){const sql=await readFile(join(project,'supabase/migrations',name),'utf8');if(!sql.startsWith('-- Hosted infrastructure:'))await db.exec(sql);}
const h=await makeHarness(db),fixture=await accountingFixture(h),day=await h.day(0);await h.inventory({id:fixture.product.box_flavors[0]},day,100);
await db.query("update elio.settings set data=data||$1::jsonb",[JSON.stringify({site_url:origin,paused:false,payment_options:[{label:'GCash',account_name:'Test',account_number:'09170000000',note:''},{label:'BDO',account_name:'Test',account_number:'0012',note:''},{label:'EastWest',account_name:'Test',account_number:'0013',note:''}]})]);
const pickerFlavor=await h.product({kind:'flavor',name:'Picker Chocolate',price_cents:1500,lead_days:0});
const pickerBox=await h.product({kind:'custom_box',name:'Picker custom box',price_cents:10000,lead_days:0});
let dropNextSaleResponse=false;let chain=Promise.resolve();const invoke=(a,p,t)=>{const result=chain.then(()=>h.api(a,p,h.ids.owner,t));chain=result.catch(()=>{});return result;};
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH,headless:true});
try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'}),errors=[];
 await ctx.exposeBinding('posRpc',async(_,{action,payload,token})=>{try{const data=await invoke(action,payload,token);if(action==='pos_create_order'&&dropNextSaleResponse){dropNextSaleResponse=false;return {data:null,error:{message:'Test: response lost after saving',code:'NETWORK'}};}return {data,error:null};}catch(e){return {data:null,error:{message:e.message,code:e.code}};}});
 await ctx.addInitScript(()=>{window.copied=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async s=>window.copied.push(s)}});});
 await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='esm.sh')return route.fulfill({contentType:'text/javascript',body:`export function createClient(){return {auth:{initialize:async()=>({}),getSession:async()=>({data:{session:{user:{id:'${h.ids.owner}',email:'owner@example.test'}}}}),onAuthStateChange:()=>{}},rpc:async(name,p)=>window.posRpc({action:p.p_action,payload:p.p_payload,token:p.p_token})}}`});if(u.origin!==origin)return route.abort();const file=resolve(root,'.'+u.pathname);if(!file.startsWith(root+sep))return route.abort();try{return route.fulfill({body:await readFile(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[extname(file)]||'application/octet-stream'});}catch{return route.fulfill({status:404,body:''});}});
 const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const chooseDate=async(name,date)=>{const field=page.locator('.accounting-date-picker').filter({has:page.locator('input[name="'+name+'"]')});await field.locator('summary').click();await field.locator('[data-date-year]').fill(date.slice(0,4));await field.locator('[data-date-year]').dispatchEvent('change');await field.locator('[data-date-month]').selectOption(date.slice(5,7));await field.locator('[data-date-value="'+date+'"]').click();await page.waitForFunction(({name,date})=>document.querySelector('input[name="'+name+'"]').value===date,{name,date});};
 await page.goto(origin+'/pos.html');await page.getByRole('button',{name:'+ Create event'}).click();
 await page.getByLabel('Event name').fill('Pop-up test');await page.getByRole('button',{name:'Save event',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 for(const name of ['Vanilla','Chocolate','Matcha']){await page.getByRole('button',{name:'+ Add flavor',exact:true}).click();await page.getByLabel('Flavor / stock unit name').fill(name);await page.getByLabel('Available pieces / units now',{exact:true}).fill('12');await page.getByRole('button',{name:'Save stock',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});}

 await page.locator('[data-stock-section=flavor]').getByRole('button',{name:'Bulk edit stock',exact:true}).click();
 await page.getByLabel('Set selected to',{exact:true}).fill('13');await page.getByRole('button',{name:'Apply quantity',exact:true}).click();
 assert.equal(await page.getByLabel('Vanilla pieces',{exact:true}).inputValue(),'13');
 await page.getByRole('button',{name:'Decrease Vanilla pieces',exact:true}).click();assert.equal(await page.getByLabel('Vanilla pieces',{exact:true}).inputValue(),'12');
 await page.getByRole('button',{name:'Increase Vanilla pieces',exact:true}).click();
 await page.getByRole('button',{name:'Save stock changes',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.locator('[data-stock-section=flavor]').getByRole('button',{name:'Bulk edit stock',exact:true}).click();await page.getByLabel('Set selected to',{exact:true}).fill('12');await page.getByRole('button',{name:'Apply quantity',exact:true}).click();
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:844});await page.locator('#dialog').screenshot({path:join(out,'bulk-stock-'+width+'.png')});assert.equal(await page.locator('#dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);}
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Save stock changes',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.getByRole('button',{name:'Build a box recipe'}).click();await page.getByLabel('Item name',{exact:true}).fill('Pop-up Trio');await page.getByLabel('Event price · PHP').fill('750');for(const name of ['Vanilla','Chocolate','Matcha'])await page.getByLabel(name+' units',{exact:true}).fill('1');await page.getByRole('button',{name:'Save item',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.getByRole('button',{name:'New sale',exact:true}).click();await page.getByRole('button',{name:'Open cash session',exact:true}).click();await page.getByLabel('Opening cash float · PHP').fill('1000');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.locator('[data-add]').click();await page.locator('[data-quantity-plus="0"]').click();assert.match(await page.locator('.cart-line-total').textContent(),/1,500\.00.*for 2/);await page.locator('[data-quantity-minus="0"]').click();assert.equal(await page.locator('[data-quantity-minus="0"]').isDisabled(),true);await page.getByRole('button',{name:'Exact amount',exact:true}).click();assert.equal(await page.getByLabel('Cash received · PHP').inputValue(),'750.00');await page.getByLabel('Cash received · PHP').fill('1');await page.getByRole('button',{name:'Complete sale',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#page-error')?.textContent.includes('Cash received is less'));assert.equal((await invoke('pos_orders',{})).length,0);await page.getByLabel('Cash received · PHP').fill('1000');dropNextSaleResponse=true;assert.equal(await page.locator('[name=method],[name=fulfillment_date],[name=pos_handed_over]').count(),0);await page.getByRole('button',{name:'Complete sale',exact:true}).click();await page.getByRole('button',{name:'Retry saving this request',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();const savedEvent=(await invoke('pos_orders',{}));assert.equal(savedEvent.length,1);assert.equal(savedEvent[0].fulfillment_status,'completed');assert.equal(savedEvent[0].fulfillment_date,day);assert.equal(savedEvent[0].delivery_cents,0);assert.match(await page.locator('#dialog-body').textContent(),/250/);await page.getByRole('button',{name:'Next sale',exact:true}).click();await page.getByRole('heading',{name:'Your sale',exact:true}).waitFor();assert.equal(await page.locator('[data-remove]').count(),0);assert.equal(await page.locator('[data-action=new-event],#show-deleted-events').count(),0);
 await page.getByRole('button',{name:'Event report',exact:true}).click();await page.getByRole('heading',{name:'Cash reconciliation'}).waitFor();assert.match(await page.locator('.metrics').textContent(),/750/);await page.screenshot({path:join(out,'event-report-desktop.png'),fullPage:true});
 const event=(await invoke('pos_events',{}))[0],snapshot=await invoke('pos_event_data',{event_id:event.id});assert(snapshot.stock.every(s=>s.remaining===11));
 await page.getByRole('button',{name:'Direct orders',exact:true}).click();await page.locator(`[data-add="${fixture.product.id}"]`).click();await chooseDate('fulfillment_date',fixture.date);await page.getByLabel('Social platform · optional').fill('Instagram');await page.getByLabel('Username / profile · optional').fill('@dmcustomer');
 await page.getByRole('button',{name:'+ Add custom item'}).click();await page.getByLabel('Custom item name').fill('DM custom cake');await page.getByLabel('Unit price · PHP').fill('250');await page.getByRole('button',{name:'Save custom item'}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.getByLabel('Fulfillment',{exact:true}).selectOption('delivery');await page.getByLabel('Delivery fee',{exact:true}).selectOption('true');await page.getByLabel('Customer pays delivery to').selectOption('courier');
 await page.getByRole('button',{name:'Review sale',exact:true}).click();await page.getByRole('button',{name:'Record sale',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();assert.match(await page.locator('#dialog-body').textContent(),/350/);await page.getByRole('button',{name:'Copy payment / order link',exact:true}).click();await page.waitForFunction(()=>window.copied.length>0);const link=await page.evaluate(()=>window.copied.at(-1));assert.match(link,/order.html#order=.*token=/);
 const direct=(await invoke('pos_orders',{})).find(o=>o.order_source==='direct');assert.equal(direct.payment_deadline,null);assert.equal(direct.buyer.social_username,'@dmcustomer');assert.equal(direct.payment_status,'awaiting_payment');
 await page.locator('#close-dialog').click();await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Customer name',{exact:true}).fill('DM Customer');await page.getByLabel('Reason for the edit').fill('Add customer name');await page.getByRole('button',{name:'Review changes',exact:true}).click();await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();await page.locator('#close-dialog').click();
 assert.equal((await invoke('get_order',{order_id:direct.id})).buyer.name,'DM Customer');
 const feeButton=()=>page.locator('[data-action="delivery-fee"][data-id="'+direct.id+'"]');
 await feeButton().click();await page.getByLabel('Customer pays delivery to').selectOption('elio');await page.getByLabel('Exact delivery fee · PHP').fill('200');await page.getByLabel('Reason / booking reference').fill('Customer chose Elio');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 assert.equal((await invoke('get_order',{order_id:direct.id})).total_cents,55000);
 await feeButton().click();await page.getByLabel('Customer pays delivery to').selectOption('courier');await page.getByLabel('Reason / booking reference').fill('Customer chose courier');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.locator('[data-action="pay-order"][data-id="'+direct.id+'"]').click();await page.getByLabel('Cash received · PHP').fill('350');await page.getByRole('button',{name:'Record payment received',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();await page.locator('#close-dialog').click();
 await feeButton().click();await page.getByLabel('Customer pays delivery to').selectOption('elio');await page.getByLabel('Reason / booking reference').fill('Final delivery booking');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await feeButton().click();await page.getByRole('button',{name:'Record delivery payment',exact:true}).click();await page.getByLabel('Payment method',{exact:true}).selectOption('BDO');await page.getByLabel('Full delivery payment received by Elio').check();await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 assert.equal((await invoke('get_order',{order_id:direct.id})).delivery_charge.state,'paid');
 await feeButton().click();await page.getByRole('button',{name:'Correct delivery payment',exact:true}).click();await page.getByLabel('The delivery payment was returned to the customer, or was recorded in error').check();await page.getByLabel('Correction reason').fill('Receipt recorded in error');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 assert.equal((await invoke('get_order',{order_id:direct.id})).delivery_charge.state,'quoted');
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.getByRole('button',{name:'New sale',exact:true}).click();await page.locator(`[data-add="${fixture.product.id}"]`).click();await page.getByLabel('Fulfillment',{exact:true}).selectOption('delivery');await page.getByLabel('Delivery fee',{exact:true}).selectOption('true');const field=page.locator('.accounting-date-picker').filter({has:page.locator('[name=fulfillment_date]')});await field.locator('summary').click();await field.locator('[data-date-month]').waitFor();await page.screenshot({path:join(out,'pos-calendar-'+width+'.png'),fullPage:true});const box=await field.locator('.accounting-calendar').boundingBox();assert(box.x>=0&&box.x+box.width<=width+1);await field.locator('[data-date-close]').click();assert.equal(await page.locator('input[type=date]').count(),0);await page.screenshot({path:join(out,`direct-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow at ${width}`);await page.locator('[data-remove]').click();}
 for(const width of [1440,390,320]){
  await page.setViewportSize({width,height:1000});await page.locator('[data-add="'+pickerBox.id+'"]').click();const picker=page.locator('.flavor-picker'),add=picker.getByRole('button',{name:'Add box',exact:true}),plus=picker.locator('[data-flavor-plus]'),minus=picker.locator('[data-flavor-minus]');
  assert.equal(await add.isDisabled(),true);assert.equal(await picker.locator('[data-flavor-minus]:not(:disabled)').count(),0);
  const first=picker.locator('[data-flavor-plus="'+fixture.product.box_flavors[0]+'"]'),second=picker.locator('[data-flavor-plus="'+pickerFlavor.id+'"]'),removeFirst=picker.locator('[data-flavor-minus="'+fixture.product.box_flavors[0]+'"]');await first.click();await first.click();await second.click();assert.equal(await add.isEnabled(),true);assert.equal(await picker.locator('[data-flavor-plus]:not(:disabled)').count(),0);
  await second.evaluate(el=>el.click());assert.equal(await picker.locator('[role=status]').textContent(),'3 of 3 selected · Remove a piece to change flavors.');
  await removeFirst.click();assert.equal(await add.isDisabled(),true);assert.equal(await picker.locator('[data-flavor-plus]:disabled').count(),0);
  await second.click();await page.locator('#dialog').screenshot({path:join(out,'flavor-picker-'+width+'.png')});assert.equal(await picker.evaluate(el=>el.scrollWidth>el.clientWidth),false);
  assert.equal(await picker.locator('input[type=number]').count(),0);await add.click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
  assert.match(await page.locator('#cart').textContent(),/Picker custom box/);
  await page.getByRole('button',{name:'Review sale',exact:true}).click();await page.getByRole('heading',{name:'Review before recording'}).waitFor({timeout:5000}).catch(async e=>{throw Error(e.message+' PAGE: '+await page.locator('#page-error').textContent());});await page.getByRole('button',{name:'Back',exact:true}).click();await page.locator('[data-remove]').click();
 }
 console.log('PASS flavor picker: +/- controls, zero minimum, aggregate three-piece maximum, re-enabled additions after removal, valid backend quote, and desktop/mobile layout.');
 // Import flavors first, then boxes, retaining custom event items and independent stock.
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'In-person sales',exact:true}).click();await page.locator('#event-select').selectOption(event.id);await page.locator('[data-add]').first().waitFor();await page.getByRole('button',{name:'Setup',exact:true}).click();
 await page.getByRole('button',{name:'Import flavors',exact:true}).click();
 await page.getByLabel('Select all',{exact:true}).check();await page.getByLabel('Set selected to',{exact:true}).fill('5');await page.getByRole('button',{name:'Apply quantity',exact:true}).click();
 assert.equal(await page.locator('[name="stock_'+pickerFlavor.id+'"]').inputValue(),'5');
 await page.getByLabel('Select all',{exact:true}).uncheck();assert.equal(await page.locator('[name="stock_'+pickerFlavor.id+'"]').isDisabled(),true);
 await page.locator('[data-import-choice][value="'+pickerFlavor.id+'"]').check();await page.getByLabel('Picker Chocolate pieces',{exact:true}).fill('0');assert.equal(await page.getByRole('button',{name:'Decrease Picker Chocolate pieces',exact:true}).isDisabled(),true);
 await page.getByLabel('Picker Chocolate pieces',{exact:true}).fill('1000000');assert.equal(await page.getByRole('button',{name:'Increase Picker Chocolate pieces',exact:true}).isDisabled(),true);
 await page.getByLabel('Picker Chocolate pieces',{exact:true}).fill('2');
 for(const [id,qty] of [[fixture.product.box_flavors[0],6],[pickerFlavor.id,2]]){await page.locator('[data-import-choice][value="'+id+'"]').check();await page.locator('[name="stock_'+id+'"]').fill(String(qty));}
 await page.locator('#dialog').screenshot({path:join(out,'import-flavors.png')});await page.getByRole('button',{name:'Import selected flavors',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.getByRole('button',{name:'Import boxes from website',exact:true}).click();for(const id of [fixture.product.id,pickerBox.id])await page.locator('[data-import-choice][value="'+id+'"]').check();await page.getByRole('button',{name:'Import selected boxes',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 let imported=await invoke('pos_event_data',{event_id:event.id});const eventBox=imported.items.find(i=>i.source_product_id===pickerBox.id),eventFixed=imported.items.find(i=>i.source_product_id===fixture.product.id),eventFirst=imported.stock.find(s=>s.source_product_id===fixture.product.box_flavors[0]),eventSecond=imported.stock.find(s=>s.source_product_id===pickerFlavor.id);
 assert.equal(eventFirst.remaining,6);assert.equal(eventSecond.remaining,2);assert.equal(eventBox.choice_stock_ids.length,2);assert(imported.items.some(i=>i.name==='Pop-up Trio'));
 await page.locator('[data-action="edit-event-item"][data-id="'+eventBox.id+'"]').click();await page.getByLabel('Event base price · PHP').fill('120');await page.getByRole('button',{name:'Save item',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.screenshot({path:join(out,'event-setup-imports.png'),fullPage:true});
 await page.getByRole('button',{name:'New sale',exact:true}).click();await page.locator('[data-add="'+eventBox.id+'"]').click();const eventPicker=page.locator('.flavor-picker');
 await eventPicker.locator('[data-flavor-plus="'+eventSecond.id+'"]').click();await eventPicker.locator('[data-flavor-plus="'+eventSecond.id+'"]').click();assert.equal(await eventPicker.locator('[data-flavor-plus="'+eventSecond.id+'"]').isDisabled(),true);await eventPicker.locator('[data-flavor-plus="'+eventFirst.id+'"]').click();await eventPicker.getByRole('button',{name:'Add box',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 assert.match(await page.locator('.cart-price').textContent(),/150\.00/);assert.equal(await page.locator('[data-quantity-plus]').isDisabled(),true);assert.equal(await page.locator('.cart-price strong').evaluate(el=>getComputedStyle(el).fontSize),'20px');
 await page.locator('[data-add="'+eventFixed.id+'"]').click();assert.equal(await page.locator('[data-quantity-plus="1"]').isDisabled(),true);await page.locator('[data-quantity-minus="1"]').evaluate(el=>el.click());assert.equal(await page.locator('.cart-quantity output').nth(1).textContent(),'1');
 assert.equal(await page.locator('[data-add="'+eventBox.id+'"]').isDisabled(),true);assert.equal(await page.locator('[data-add="'+eventFixed.id+'"]').isDisabled(),true);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});if(width<650){if(await page.getByRole('button',{name:'← Back to items',exact:true}).isVisible())await page.getByRole('button',{name:'← Back to items',exact:true}).click();assert.equal(await page.locator('.checkout-panel').isVisible(),false);await page.screenshot({path:join(out,'cashier-catalog-'+width+'.png'),fullPage:true});await page.getByRole('button',{name:'View sale',exact:true}).click();assert.equal(await page.locator('.catalog-panel').isVisible(),false);assert.equal(await page.locator('.tabs').evaluate(el=>getComputedStyle(el).position),'fixed');}await page.locator('#cart').screenshot({path:join(out,'cart-prices-'+width+'.png')});await page.screenshot({path:join(out,'cashier-'+width+'.png'),fullPage:true});assert.equal(await page.locator('[name=method],[name=fulfillment_date],[name=pos_handed_over]').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}

 await page.setViewportSize({width:1440,height:1000});await page.locator('[data-payment-method=GCash]').click();assert.equal(await page.locator('[name=cash_received]').count(),0);await page.locator('[data-payment-method=cash]').click();await page.getByLabel('Cash received · PHP').fill('1000');await page.screenshot({path:join(out,'event-fast-checkout.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('[name=method],[name=fulfillment_date],[name=pos_handed_over]').count(),0);await page.getByRole('button',{name:'Complete sale',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();await page.locator('#dialog').screenshot({path:join(out,'mobile-sale-saved.png')});await page.getByRole('button',{name:'Next sale',exact:true}).click();assert.equal(await page.locator('.catalog-panel').isVisible(),true);assert.equal(await page.locator('.checkout-panel').isVisible(),false);assert.equal(await page.locator('[data-remove]').count(),0);await page.setViewportSize({width:1440,height:1000});
 imported=await invoke('pos_event_data',{event_id:event.id});assert.equal(imported.stock.find(s=>s.id===eventFirst.id).remaining,2);assert.equal(imported.stock.find(s=>s.id===eventSecond.id).remaining,0);
 await page.getByRole('button',{name:'Setup',exact:true}).click();await page.locator('[data-action="delete-event-stock"][data-id="'+eventSecond.id+'"]').click();await page.getByRole('button',{name:'Delete stock item',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.locator('[data-action="delete-event-item"][data-id="'+eventBox.id+'"]').click();await page.getByRole('button',{name:'Delete event item',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.getByRole('button',{name:'Edit event',exact:true}).click();await chooseDate('ends_on',await h.day(1));assert.equal(await page.locator('[name=ends_on]').inputValue(),await h.day(1));await page.locator('#close-dialog').click();
 await page.getByRole('button',{name:'Delete event',exact:true}).click();await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});assert.equal(await page.locator('#event-select option[value="'+event.id+'"]').count(),0);
 await page.getByLabel('Show deleted events').check();await page.locator('#event-select option[value="'+event.id+'"]').waitFor({state:'attached'});await page.locator('#event-select').selectOption(event.id);await page.getByRole('button',{name:'Event report',exact:true}).click();await page.getByRole('heading',{name:'Cash reconciliation'}).waitFor();assert.match(await page.locator('.metrics').textContent(),/1,000\.00/);
 await chooseDate('report_date',await h.day(1));await page.waitForFunction(()=>document.querySelector('.metrics')?.textContent.includes('Not opened'));await chooseDate('report_date',day);await page.waitForFunction(()=>document.querySelector('.metrics')?.textContent.includes('1,000.00'));
 const preserved=await invoke('pos_event_report',{event_id:event.id,date:day});assert.equal(preserved.sales[0].total_cents,100000);
 console.log('PASS event management: imported flavors and quantities, fixed/custom boxes, stock limits, custom pricing, prominent unit/line prices, branded calendars, deletion and retained reports.');


 await page.getByRole('button',{name:'Setup',exact:true}).click();await page.getByRole('button',{name:'+ Create event',exact:true}).click();await page.getByLabel('Event name').fill('Separate stock test');await page.getByRole('button',{name:'Save event',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 assert.equal(await page.locator('[data-stock-section=item]').count(),0);
 await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByLabel('Product name',{exact:true}).fill('Krisp Nori Pouch');await page.getByLabel('Event price · PHP',{exact:true}).fill('100');await page.getByLabel('Available stock',{exact:true}).fill('100');
 await page.getByLabel('Flavors',{exact:true}).selectOption('flavors');assert.equal(await page.getByLabel('Product name',{exact:true}).inputValue(),'Krisp Nori Pouch');assert.equal(await page.getByLabel('Base event price · PHP',{exact:true}).inputValue(),'100');await page.getByLabel('Flavors',{exact:true}).selectOption('simple');assert.equal(await page.getByLabel('Available stock',{exact:true}).inputValue(),'100');
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:844});await page.locator('#dialog').screenshot({path:join(out,'single-stock-item-'+width+'.png')});assert.equal(await page.locator('#dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);}
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Save product',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});assert.equal(await page.locator('[data-stock-section=item]').count(),0);assert.doesNotMatch(await page.locator('[data-stock-section=flavor]').textContent(),/Krisp Nori Pouch/);
 const noriEvent=(await invoke('pos_events',{})).find(e=>e.name==='Separate stock test');
 await page.getByRole('button',{name:'New sale',exact:true}).click();await page.getByRole('button',{name:'Open cash session',exact:true}).click();await page.getByLabel('Opening cash float · PHP').fill('0');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});await page.locator('[data-add]').click();await page.getByRole('button',{name:'Exact amount',exact:true}).click();await page.getByRole('button',{name:'Complete sale',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();await page.getByRole('button',{name:'Next sale',exact:true}).click();assert.equal((await invoke('pos_event_data',{event_id:noriEvent.id})).stock[0].remaining,99);
 await page.getByRole('button',{name:'Setup',exact:true}).click();await page.screenshot({path:join(out,'separate-stock-setup.png'),fullPage:true});
 console.log('PASS stock controls: bulk selection and save, quantity boundaries, desktop/mobile layout, distinct stock groups and one nori pouch sale deducts 100 to 99.');
 // Individual products keep their own selectable flavors, stock and surcharges.
 await page.getByRole('button',{name:'+ Add product',exact:true}).click();await page.getByLabel('Flavors',{exact:true}).selectOption('flavors');await page.getByLabel('Product name',{exact:true}).fill('Chunkies singles');await page.getByLabel('Base event price · PHP',{exact:true}).fill('140');
 const fillFlavor=async(index,name,stock,surcharge)=>{const row=page.locator('[data-variant-row]').nth(index);await row.locator('[name^=flavor_name_]').fill(name);await row.locator('[name^=flavor_stock_]').fill(stock);await row.locator('[name^=flavor_surcharge_]').fill(surcharge);};
 await fillFlavor(0,'Classic Chocochip','2','0');await page.locator('#dialog').getByRole('button',{name:'+ Add flavor',exact:true}).click();await fillFlavor(1,'Chocolate','1','10');await page.locator('#dialog').getByRole('button',{name:'+ Add flavor',exact:true}).click();await fillFlavor(2,'Matchadamia','0','20');
 assert.equal(await page.locator('[data-variant-total]').textContent(),'Total available stock: 3');
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await page.locator('#dialog').screenshot({path:join(out,'product-flavor-editor-'+width+'.png')});assert.equal(await page.locator('#dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);}
 await page.getByRole('button',{name:'Save product',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});await page.setViewportSize({width:1440,height:1000});
 const variantData=await invoke('pos_event_data',{event_id:noriEvent.id}),variantProduct=variantData.items.find(p=>p.name==='Chunkies singles'),variantStock=variantData.stock.filter(s=>s.variant_item_id===variantProduct.id),classic=variantStock.find(s=>s.name==='Classic Chocochip'),chocolate=variantStock.find(s=>s.name==='Chocolate'),matcha=variantStock.find(s=>s.name==='Matchadamia');
 assert.equal(variantProduct.remaining,3);assert.doesNotMatch(await page.locator('[data-stock-section=flavor]').textContent(),/Classic Chocochip/);assert.equal(await page.locator('[data-stock-section=item]').count(),0);
 await page.getByRole('button',{name:'New sale',exact:true}).click();await page.locator('[data-add="'+variantProduct.id+'"]').click();assert.equal(await page.locator('[data-item-flavor="'+matcha.id+'"]').isDisabled(),true);assert.match(await page.locator('[data-item-flavor="'+chocolate.id+'"]').textContent(),/150\.00/);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await page.locator('#dialog').screenshot({path:join(out,'product-flavor-picker-'+width+'.png')});assert.equal(await page.locator('#dialog').evaluate(el=>el.scrollWidth>el.clientWidth),false);}
 await page.setViewportSize({width:1440,height:1000});await page.locator('[data-item-flavor="'+chocolate.id+'"]').click();assert.match(await page.locator('#cart').textContent(),/Chocolate/);assert.match(await page.locator('.cart-price').textContent(),/150\.00/);assert.equal(await page.locator('[data-quantity-plus="0"]').isDisabled(),true);
 await page.locator('[data-add="'+variantProduct.id+'"]').click();assert.equal(await page.locator('[data-item-flavor="'+chocolate.id+'"]').isDisabled(),true);await page.locator('[data-item-flavor="'+classic.id+'"]').click();await page.locator('[data-quantity-plus="1"]').click();assert.equal(await page.locator('[data-add="'+variantProduct.id+'"]').isDisabled(),true);await page.locator('[data-quantity-minus="1"]').click();assert.equal(await page.locator('[data-add="'+variantProduct.id+'"]').isDisabled(),false);await page.locator('[data-quantity-plus="1"]').click();
 await page.getByLabel('Cash received · PHP').fill('500');await page.getByRole('button',{name:'Complete sale',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();assert.match(await page.locator('#dialog-body').textContent(),/70\.00/);await page.getByRole('button',{name:'Next sale',exact:true}).click();
 const afterVariants=await invoke('pos_event_data',{event_id:noriEvent.id});assert.equal(afterVariants.items.find(p=>p.id===variantProduct.id).remaining,0);assert(afterVariants.stock.filter(s=>s.variant_item_id===variantProduct.id).every(s=>s.remaining===0));assert.equal(afterVariants.stock.find(s=>s.name==='Krisp Nori Pouch').remaining,99);
 await page.getByRole('button',{name:'Setup',exact:true}).click();await page.locator('[data-action=edit-event-item][data-id="'+variantProduct.id+'"]').click();assert.equal(await page.locator('[data-variant-row]').count(),3);await page.locator('[data-variant-row="'+chocolate.id+'"] [name^=flavor_stock_]').fill('5');await page.locator('[data-variant-row="'+chocolate.id+'"] [name^=flavor_surcharge_]').fill('15');await page.getByRole('button',{name:'Save product',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 console.log('PASS individual product flavors: three-column setup, own stock, surcharges, tap-to-add, sold-out/cart limits, exact deductions and mobile layouts.');

 assert.deepEqual(errors,[]);console.log('PASS POS browser: event setup, recipe stock, cash/change, report, optional DM contacts, payment links, editing, and four viewport widths.');
 await ctx.close();
}finally{await browser.close();await db.close();}
