import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir,mkdir} from 'node:fs/promises';
import {resolve,join,extname,sep} from 'node:path';
import {makeHarness} from '../backend/helpers.mjs';
import {accountingFixture} from '../backend/accounting-fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require(join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'playwright'));
const dep=createRequire(join(process.env.PGLITE_PACKAGE_ROOT,'package.json')),{PGlite}=dep('@electric-sql/pglite'),{pgcrypto}=dep('@electric-sql/pglite/contrib/pgcrypto');
const db=new PGlite({extensions:{pgcrypto}}),project=resolve(import.meta.dirname,'../..'),root=join(project,'dist'),origin='https://pos.test',out=join(project,'test-results/pos');await mkdir(out,{recursive:true});
await db.exec(await readFile(join(project,'tests/backend/bootstrap.sql'),'utf8'));
for(const name of (await readdir(join(project,'supabase/migrations'))).filter(n=>n.endsWith('.sql')).sort()){const sql=await readFile(join(project,'supabase/migrations',name),'utf8');if(!sql.startsWith('-- Hosted infrastructure:'))await db.exec(sql);}
const h=await makeHarness(db),fixture=await accountingFixture(h),day=await h.day(0);await h.inventory({id:fixture.product.box_flavors[0]},day,100);
await db.query("update elio.settings set data=data||$1::jsonb",[JSON.stringify({site_url:origin,paused:false,payment_options:[{label:'GCash',account_name:'Test',account_number:'09170000000',note:''},{label:'BDO',account_name:'Test',account_number:'0012',note:''},{label:'EastWest',account_name:'Test',account_number:'0013',note:''}]})]);
let chain=Promise.resolve();const invoke=(a,p,t)=>{const result=chain.then(()=>h.api(a,p,h.ids.owner,t));chain=result.catch(()=>{});return result;};
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH,headless:true});
try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'}),errors=[];
 await ctx.exposeBinding('posRpc',async(_,{action,payload,token})=>{try{return {data:await invoke(action,payload,token),error:null};}catch(e){return {data:null,error:{message:e.message,code:e.code}};}});
 await ctx.addInitScript(()=>{window.copied=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async s=>window.copied.push(s)}});});
 await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='esm.sh')return route.fulfill({contentType:'text/javascript',body:`export function createClient(){return {auth:{initialize:async()=>({}),getSession:async()=>({data:{session:{user:{id:'${h.ids.owner}',email:'owner@example.test'}}}}),onAuthStateChange:()=>{}},rpc:async(name,p)=>window.posRpc({action:p.p_action,payload:p.p_payload,token:p.p_token})}}`});if(u.origin!==origin)return route.abort();const file=resolve(root,'.'+u.pathname);if(!file.startsWith(root+sep))return route.abort();try{return route.fulfill({body:await readFile(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[extname(file)]||'application/octet-stream'});}catch{return route.fulfill({status:404,body:''});}});
 const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(origin+'/pos.html');await page.getByRole('button',{name:'+ Create event'}).click();
 await page.getByLabel('Event name').fill('Pop-up test');await page.getByRole('button',{name:'Save event',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 for(const name of ['Vanilla','Chocolate','Matcha']){await page.getByRole('button',{name:'+ Add flavor / stock item'}).click();await page.getByLabel('Flavor / stock unit name').fill(name);await page.getByLabel('Available pieces / units now').fill('12');await page.getByRole('button',{name:'Save stock',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});}
 await page.getByRole('button',{name:'+ Add event item'}).click();await page.getByLabel('Item name',{exact:true}).fill('Pop-up Trio');await page.getByLabel('Event price · PHP').fill('750');for(const name of ['Vanilla','Chocolate','Matcha'])await page.getByLabel(name+' units',{exact:true}).fill('1');await page.getByRole('button',{name:'Save item',exact:true}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.getByRole('button',{name:'New sale',exact:true}).click();await page.getByRole('button',{name:'Open cash session',exact:true}).click();await page.getByLabel('Opening cash float · PHP').fill('1000');await page.locator('#dialog button[type=submit]').click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.locator('[data-add]').click();await page.getByLabel('Cash received · PHP').fill('1000');await page.getByRole('button',{name:'Review sale',exact:true}).click();await page.getByRole('button',{name:'Record sale',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();assert.match(await page.locator('#dialog-body').textContent(),/250/);await page.locator('#close-dialog').click();
 await page.getByRole('button',{name:'Event report',exact:true}).click();await page.getByRole('heading',{name:'Cash reconciliation'}).waitFor();assert.match(await page.locator('.metrics').textContent(),/750/);await page.screenshot({path:join(out,'event-report-desktop.png'),fullPage:true});
 const event=(await invoke('pos_events',{}))[0],snapshot=await invoke('pos_event_data',{event_id:event.id});assert(snapshot.stock.every(s=>s.remaining===11));
 await page.getByRole('button',{name:'Direct orders',exact:true}).click();await page.locator(`[data-add="${fixture.product.id}"]`).click();await page.getByLabel('Fulfillment date',{exact:true}).fill(fixture.date);await page.getByLabel('Fulfillment date',{exact:true}).dispatchEvent('change');await page.getByLabel('Social platform · optional').fill('Instagram');await page.getByLabel('Username / profile · optional').fill('@dmcustomer');
 await page.getByRole('button',{name:'+ Add custom item'}).click();await page.getByLabel('Custom item name').fill('DM custom cake');await page.getByLabel('Unit price · PHP').fill('250');await page.getByRole('button',{name:'Save custom item'}).click();await page.locator('#dialog:not([open])').waitFor({state:'attached'});
 await page.getByRole('button',{name:'Review sale',exact:true}).click();await page.getByRole('button',{name:'Record sale',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();assert.match(await page.locator('#dialog-body').textContent(),/350/);await page.getByRole('button',{name:'Copy payment / order link',exact:true}).click();await page.waitForFunction(()=>window.copied.length>0);const link=await page.evaluate(()=>window.copied.at(-1));assert.match(link,/order.html#order=.*token=/);
 const direct=(await invoke('pos_orders',{})).find(o=>o.order_source==='direct');assert.equal(direct.payment_deadline,null);assert.equal(direct.buyer.social_username,'@dmcustomer');assert.equal(direct.payment_status,'awaiting_payment');
 await page.locator('#close-dialog').click();await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Customer name',{exact:true}).fill('DM Customer');await page.getByLabel('Reason for the edit').fill('Add customer name');await page.getByRole('button',{name:'Review changes',exact:true}).click();await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('heading',{name:'Order saved'}).waitFor();await page.locator('#close-dialog').click();
 assert.equal((await invoke('get_order',{order_id:direct.id})).buyer.name,'DM Customer');
 for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.getByRole('button',{name:'New sale',exact:true}).click();await page.locator(`[data-add="${fixture.product.id}"]`).click();await page.screenshot({path:join(out,`direct-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow at ${width}`);await page.locator('[data-remove]').click();}
 assert.deepEqual(errors,[]);console.log('PASS POS browser: event setup, recipe stock, cash/change, report, optional DM contacts, payment links, editing, and four viewport widths.');
 await ctx.close();
}finally{await browser.close();await db.close();}
