import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {resolve,join,extname,sep} from 'node:path';
import {makeHarness} from '../backend/helpers.mjs';
import {accountingFixture} from '../backend/accounting-fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require(join(process.env.PLAYWRIGHT_PACKAGE_ROOT,'playwright'));
const dep=createRequire(join(process.env.PGLITE_PACKAGE_ROOT,'package.json')),{PGlite}=dep('@electric-sql/pglite'),{pgcrypto}=dep('@electric-sql/pglite/contrib/pgcrypto');
const db=new PGlite({extensions:{pgcrypto}}),project=resolve(import.meta.dirname,'../..'),root=join(project,'dist'),origin='https://loading.test',out=join(project,'test-results/shop-loading');await mkdir(out,{recursive:true});
await db.exec(await readFile(join(project,'tests/backend/bootstrap.sql'),'utf8'));
for(const name of (await readdir(join(project,'supabase/migrations'))).filter(n=>n.endsWith('.sql')).sort()){const sql=await readFile(join(project,'supabase/migrations',name),'utf8');if(!sql.startsWith('-- Hosted infrastructure:'))await db.exec(sql);}
const h=await makeHarness(db);
await db.query("update elio.settings set data=data||$1::jsonb",[JSON.stringify({paused:false,production_weekdays:[0,1,2,3,4,5,6],fulfillment_weekdays:[0,1,2,3,4,5,6],blocked_dates:[],pickup_blocked_dates:[],delivery_blocked_dates:[],cutoff_time:''})]);
const fixture=await accountingFixture(h),catalog=await h.api('catalog');
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE_PATH,headless:true}),results=[];
try{
for(const [width,scenario] of [[320,'normal'],[390,'saved-cart'],[768,'normal'],[1440,'normal'],[390,'failure-retry'],[390,'empty'],[390,'auth-failure'],[390,'order-link']]){
 const errors=[],ctx=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});let release,started,fail=scenario==='failure-retry',authFail=scenario==='auth-failure',authChecks=0;const gate=new Promise(r=>release=r),pending=new Promise(r=>started=r);
 await ctx.exposeBinding('loadingRpc',async(_,{action})=>{if(action==='catalog'){started();await gate;if(fail){fail=false;return {data:null,error:{message:'Simulated connection interruption'}};}return {data:scenario==='empty'?{...catalog,products:[]}:catalog,error:null};}if(action==='get_order'){await gate;return {data:null,error:{message:'Order not found'}};}return {data:{},error:null};});
 await ctx.exposeBinding('loadingAuth',()=>{if(authFail&&++authChecks===2){authFail=false;throw new Error('Simulated expired session connection');}return {data:{session:null}};});
 await ctx.addInitScript(({saved,product})=>{localStorage.setItem('elio-newsletter-popup-v1',JSON.stringify({state:'submitted',firstVisit:Date.now(),updatedAt:Date.now()}));if(saved)sessionStorage.setItem('elio-checkout-v1',JSON.stringify({saved_at:Date.now(),items:[{product_id:product.id,name:product.name,quantity:2,selections:{},unit_price_cents:product.price_cents}]}));},{saved:scenario==='saved-cart',product:fixture.product});
 await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='esm.sh')return route.fulfill({contentType:'text/javascript',body:`export function createClient(){return {auth:{initialize:async()=>({}),getSession:()=>window.loadingAuth(),onAuthStateChange:()=>{}},rpc:async(n,p)=>window.loadingRpc({action:p.p_action})}}`});if(u.origin!==origin)return route.abort();const file=resolve(root,'.'+u.pathname);if(!file.startsWith(root+sep))return route.abort();try{return route.fulfill({body:await readFile(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png'})[extname(file)]||'application/octet-stream'});}catch{return route.fulfill({status:404,body:''});}});
 const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/order.html'+(scenario==='order-link'?'#order=00000000-0000-4000-8000-000000000000':''));
 if(scenario==='auth-failure'){await page.getByRole('button',{name:'Try again',exact:true}).waitFor();assert.equal(await page.locator('#app').getAttribute('aria-busy'),null);assert.equal(await page.locator('.shop-loading').count(),0);release();await page.getByRole('button',{name:'Try again',exact:true}).click();await page.locator('#product-grid').waitFor();}
 else {await pending;if(scenario==='order-link'){assert.match(await page.locator('#app').innerText(),/Opening your order/);assert.equal(await page.locator('.shop-loading').count(),0);}else{assert.equal(await page.locator('#app').getAttribute('aria-busy'),'true');assert.equal(await page.locator('.shop-loading .elio-product-card').count(),4);assert.equal(await page.locator('.shop-loading [aria-hidden=true][inert]').count(),1);assert.equal(await page.locator('.shop-loading button:enabled').count(),0);await page.evaluate(()=>document.fonts.ready);}
 const before=scenario==='order-link'?null:await page.locator('.shop-loading .elio-product-media').first().boundingBox();
 if(width===390&&scenario==='saved-cart')await page.screenshot({path:join(out,'loading-phone.png'),fullPage:true});release();
 if(scenario==='failure-retry'){await page.getByRole('button',{name:'Try again',exact:true}).waitFor();assert.equal(await page.locator('.shop-loading').count(),0);assert.equal(await page.locator('#app').getAttribute('aria-busy'),null);await page.getByRole('button',{name:'Try again',exact:true}).click();}
 if(scenario==='order-link')await page.getByRole('heading',{name:'We couldn’t open that order',exact:true}).waitFor();else if(scenario==='empty')await page.getByRole('heading',{name:'No boxes are listed right now.',exact:true}).waitFor();else{await page.locator('#product-grid .elio-product-card').first().waitFor();const after=await page.locator('#product-grid .elio-product-media').first().boundingBox();if(Math.abs(before.y-after.y)>3)console.log(JSON.stringify(await page.locator("#app").evaluate(el=>({text:el.innerText.slice(0,1300),parts:[...el.querySelectorAll(".notice,.fulfillment-bar,.section-heading,#box-category-filters")].map(n=>({text:n.textContent,rect:n.getBoundingClientRect().toJSON()}))}))));assert.ok(Math.abs(before.y-after.y)<=3,`First product shifted ${after.y-before.y}px at ${width}`);results.push({width,scenario,firstProductTopBefore:before.y,firstProductTopAfter:after.y});}
 }
 assert.equal(await page.locator('#app').getAttribute('aria-busy'),null);assert.equal(await page.locator('.shop-loading').count(),0);if(scenario==='saved-cart'){const saved=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('elio-checkout-v1')));assert.equal(saved.items[0].quantity,2);assert.equal(saved.items[0].product_id,fixture.product.id);}
 const scroll=await page.evaluate(()=>document.documentElement.scrollWidth);assert.equal(scroll,width);assert.deepEqual(errors,[]);results.push({width,scenario,pass:true});await ctx.close();
}
const ctx=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:900}});await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();try{return route.fulfill({body:await readFile(join(root,u.pathname)),contentType:extname(u.pathname)==='.html'?'text/html':'text/css'});}catch{return route.abort();}});const p=await ctx.newPage();await p.goto(origin+'/order.html');assert.equal(await p.locator('.shop-loading').isVisible(),false);assert.ok(await p.locator('#app noscript p').isVisible());await ctx.close();results.push({scenario:'no-JavaScript',pass:true});
await writeFile(join(out,'results.json'),JSON.stringify(results,null,2));console.log('PASS shop loading: 9 scenarios, four widths, failure/retry, empty catalog, saved basket, order link and no-JavaScript fallback.');
}finally{await browser.close();await db.close();}
